# Generated by Django 3.0.3 on 2020-06-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('mName', models.CharField(max_length=20)),
                ('mEmail', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('mPhone', models.IntegerField(max_length=10)),
                ('mPassword', models.CharField(max_length=30)),
            ],
        ),
    ]
