# Generated by Django 3.0.3 on 2020-06-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mPhone',
            field=models.IntegerField(),
        ),
    ]
