# Generated by Django 3.0.3 on 2020-06-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200616_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mPhone',
            field=models.IntegerField(null=True),
        ),
    ]
