# Generated by Django 3.0.3 on 2020-06-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200618_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mPhone',
            field=models.IntegerField(default=10),
        ),
    ]
