# Generated by Django 3.0.3 on 2020-06-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mUsername',
            field=models.CharField(default='hthd', max_length=20),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
