# Generated by Django 3.0.3 on 2020-06-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20200623_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mEmail',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='mUsername',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
