# Generated by Django 3.0.3 on 2020-07-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20200623_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mPhone',
            field=models.CharField(max_length=10),
        ),
    ]
